CREATE TABLE usuarios (
    usuario_id BIGSERIAL PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    ref VARCHAR(150) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    contrasena VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
    fecha_ultima_actualizacion TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
    ultimo_inicio_sesion TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP 
);