server:
  port: 8080

logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG
    '[reactor.netty.http.client]': DEBUG
 
spring:
  application:
    name: "gateway-ms"
  cloud:
    config:
      enabled: false
    gateway:
      routes:
      - id: costumer-ms
        uri: http://localhost:4001
        predicates:
        - Path=/customers/**
      - id: plan-ms
        uri: http://localhost:4002
        predicates:
        - Path=/planes/**
      - id: plan-ms-miembros
        uri: http://localhost:4002
        predicates:
        - Path=/miembros/**

